"""

Revision ID: 0d60c1f1dbc8
Revises: 1d756213b019
Create Date: 2026-02-17 21:19:10.203265

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d60c1f1dbc8'
down_revision: str | Sequence[str] | None = '1d756213b019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ancillary_lands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ancillary_lands_pnu'), 'ancillary_lands', ['pnu'], unique=False)
    op.create_table('land_and_forest_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('jimok_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('ownership_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('owner_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'data_year', name='uq_land_forest_pnu_year')
    )
    op.create_index(op.f('ix_land_and_forest_infos_pnu'), 'land_and_forest_infos', ['pnu'], unique=False)
    op.create_table('land_ownerships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('base_year_month', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('co_owner_seq', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('ownership_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('ownership_change_reason', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('ownership_change_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('owner_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'co_owner_seq', name='uq_land_ownership_pnu_seq')
    )
    op.create_index(op.f('ix_land_ownerships_pnu'), 'land_ownerships', ['pnu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_land_ownerships_pnu'), table_name='land_ownerships')
    op.drop_table('land_ownerships')
    op.drop_index(op.f('ix_land_and_forest_infos_pnu'), table_name='land_and_forest_infos')
    op.drop_table('land_and_forest_infos')
    op.drop_index(op.f('ix_ancillary_lands_pnu'), table_name='ancillary_lands')
    op.drop_table('ancillary_lands')
    # ### end Alembic commands ###
