"""공공데이터 DB 개선: 중복인덱스 제거, 복합인덱스 추가, 유니크제약 추가, BigInteger 변환

Revision ID: 1494dcb4fa70
Revises: 675a0788be23
Create Date: 2026-02-17 19:53:46.561567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1494dcb4fa70'
down_revision: Union[str, Sequence[str], None] = '675a0788be23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_administrative_divisions_parent_code'), 'administrative_divisions', ['parent_code'], unique=False)
    op.drop_index(op.f('ix_building_register_ancillary_lots_atch_pnu'), table_name='building_register_ancillary_lots')
    op.create_unique_constraint('uq_bldrgst_ancillary_lot', 'building_register_ancillary_lots', ['mgm_bldrgst_pk', 'atch_pnu'])
    op.create_unique_constraint('uq_bldrgst_area', 'building_register_areas', ['mgm_bldrgst_pk', 'dong_name', 'ho_name', 'floor_no', 'exclu_common_type'])
    op.create_unique_constraint('uq_bldrgst_floor_detail', 'building_register_floor_details', ['mgm_bldrgst_pk', 'floor_type_name', 'floor_no'])
    op.drop_index(op.f('ix_building_register_generals_mgm_bldrgst_pk'), table_name='building_register_generals')
    op.drop_index(op.f('ix_building_register_headers_mgm_bldrgst_pk'), table_name='building_register_headers')
    op.drop_index(op.f('ix_land_and_forest_infos_pnu'), table_name='land_and_forest_infos')
    op.alter_column('land_characteristics', 'official_price',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('ix_land_characteristics_pnu'), table_name='land_characteristics')
    op.alter_column('land_ownerships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_land_ownerships_pnu'), table_name='land_ownerships')
    op.drop_index(op.f('ix_land_use_plans_pnu'), table_name='land_use_plans')
    op.drop_constraint(op.f('uq_land_use_pnu_year'), 'land_use_plans', type_='unique')
    op.create_unique_constraint('uq_land_use_pnu_year_name', 'land_use_plans', ['pnu', 'data_year', 'use_district_name'])
    op.alter_column('official_land_prices', 'price_per_sqm',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_index(op.f('ix_official_land_prices_pnu'), table_name='official_land_prices')
    op.drop_index(op.f('ix_real_estate_rentals_building_name'), table_name='real_estate_rentals')
    op.drop_index(op.f('ix_real_estate_rentals_sgg_code'), table_name='real_estate_rentals')
    op.drop_index(op.f('ix_real_estate_rentals_transaction_date'), table_name='real_estate_rentals')
    op.create_index('ix_rentals_sgg_txdate', 'real_estate_rentals', ['sgg_code', 'transaction_date'], unique=False)
    op.drop_index(op.f('ix_real_estate_sales_building_name'), table_name='real_estate_sales')
    op.drop_index(op.f('ix_real_estate_sales_sgg_code'), table_name='real_estate_sales')
    op.drop_index(op.f('ix_real_estate_sales_transaction_date'), table_name='real_estate_sales')
    op.create_index('ix_sales_sgg_txdate', 'real_estate_sales', ['sgg_code', 'transaction_date'], unique=False)
    op.drop_index(op.f('ix_road_center_lines_source_id'), table_name='road_center_lines')
    op.create_unique_constraint('uq_road_center_line_source_id', 'road_center_lines', ['source_id'])
    op.drop_index(op.f('ix_use_region_districts_source_id'), table_name='use_region_districts')
    op.create_unique_constraint('uq_use_region_district_source_id', 'use_region_districts', ['source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_use_region_district_source_id', 'use_region_districts', type_='unique')
    op.create_index(op.f('ix_use_region_districts_source_id'), 'use_region_districts', ['source_id'], unique=False)
    op.drop_constraint('uq_road_center_line_source_id', 'road_center_lines', type_='unique')
    op.create_index(op.f('ix_road_center_lines_source_id'), 'road_center_lines', ['source_id'], unique=False)
    op.drop_index('ix_sales_sgg_txdate', table_name='real_estate_sales')
    op.create_index(op.f('ix_real_estate_sales_transaction_date'), 'real_estate_sales', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_real_estate_sales_sgg_code'), 'real_estate_sales', ['sgg_code'], unique=False)
    op.create_index(op.f('ix_real_estate_sales_building_name'), 'real_estate_sales', ['building_name'], unique=False)
    op.drop_index('ix_rentals_sgg_txdate', table_name='real_estate_rentals')
    op.create_index(op.f('ix_real_estate_rentals_transaction_date'), 'real_estate_rentals', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_real_estate_rentals_sgg_code'), 'real_estate_rentals', ['sgg_code'], unique=False)
    op.create_index(op.f('ix_real_estate_rentals_building_name'), 'real_estate_rentals', ['building_name'], unique=False)
    op.create_index(op.f('ix_official_land_prices_pnu'), 'official_land_prices', ['pnu'], unique=False)
    op.alter_column('official_land_prices', 'price_per_sqm',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint('uq_land_use_pnu_year_name', 'land_use_plans', type_='unique')
    op.create_unique_constraint(op.f('uq_land_use_pnu_year'), 'land_use_plans', ['pnu', 'data_year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_land_use_plans_pnu'), 'land_use_plans', ['pnu'], unique=False)
    op.create_index(op.f('ix_land_ownerships_pnu'), 'land_ownerships', ['pnu'], unique=False)
    op.alter_column('land_ownerships', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_land_characteristics_pnu'), 'land_characteristics', ['pnu'], unique=False)
    op.alter_column('land_characteristics', 'official_price',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('ix_land_and_forest_infos_pnu'), 'land_and_forest_infos', ['pnu'], unique=False)
    op.create_index(op.f('ix_building_register_headers_mgm_bldrgst_pk'), 'building_register_headers', ['mgm_bldrgst_pk'], unique=False)
    op.create_index(op.f('ix_building_register_generals_mgm_bldrgst_pk'), 'building_register_generals', ['mgm_bldrgst_pk'], unique=False)
    op.drop_constraint('uq_bldrgst_floor_detail', 'building_register_floor_details', type_='unique')
    op.drop_constraint('uq_bldrgst_area', 'building_register_areas', type_='unique')
    op.drop_constraint('uq_bldrgst_ancillary_lot', 'building_register_ancillary_lots', type_='unique')
    op.create_index(op.f('ix_building_register_ancillary_lots_atch_pnu'), 'building_register_ancillary_lots', ['atch_pnu'], unique=False)
    op.drop_index(op.f('ix_administrative_divisions_parent_code'), table_name='administrative_divisions')
    # ### end Alembic commands ###
