"""add pnu lat lng to reports

Revision ID: 2e14c8b34c3a
Revises: edf82972b42c
Create Date: 2026-02-22 14:33:23.036730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e14c8b34c3a'
down_revision: Union[str, Sequence[str], None] = 'edf82972b42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=True))
    op.add_column('reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_reports_pnu'), 'reports', ['pnu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_pnu'), table_name='reports')
    op.drop_column('reports', 'longitude')
    op.drop_column('reports', 'latitude')
    op.drop_column('reports', 'pnu')
    # ### end Alembic commands ###
