"""Add address column to lots and populate from admin tables

Revision ID: 3dde80897250
Revises: 0d27d561ed02
Create Date: 2026-02-19 01:36:49.985527

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3dde80897250'
down_revision: str | Sequence[str] | None = '0d27d561ed02'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('lots', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))

    # 기존 데이터에 주소 채우기: 행정경계 테이블 + PNU 지번 변환
    op.execute(sa.text("""
        UPDATE lots l
        SET address = CONCAT_WS(' ',
            s.name,
            g.name,
            e.name,
            CASE WHEN SUBSTRING(l.pnu, 11, 1) = '2' THEN '산 ' ELSE '' END ||
            CAST(SUBSTRING(l.pnu, 12, 4) AS INTEGER)::TEXT ||
            CASE WHEN CAST(SUBSTRING(l.pnu, 16, 4) AS INTEGER) > 0
                 THEN '-' || CAST(SUBSTRING(l.pnu, 16, 4) AS INTEGER)::TEXT
                 ELSE ''
            END
        )
        FROM administrative_sidos s, administrative_sggs g, administrative_emds e
        WHERE s.sido_code = SUBSTRING(l.pnu, 1, 2)
          AND g.sgg_code = SUBSTRING(l.pnu, 1, 5)
          AND (e.emd_code = SUBSTRING(l.pnu, 1, 8)
               OR e.emd_code = SUBSTRING(l.pnu, 1, 10))
          AND l.address IS NULL
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'address')
    # ### end Alembic commands ###
