"""

Revision ID: 4e696ca65b61
Revises: 42b7e2161ef4
Create Date: 2026-02-18 00:41:21.527075

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e696ca65b61'
down_revision: str | Sequence[str] | None = '42b7e2161ef4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrative_emds_emd_code'), table_name='administrative_emds')
    op.create_unique_constraint(None, 'administrative_emds', ['emd_code'])
    op.drop_constraint(op.f('administrative_emds_sgg_code_fkey'), 'administrative_emds', type_='foreignkey')
    op.drop_index(op.f('ix_administrative_sggs_sgg_code'), table_name='administrative_sggs')
    op.create_unique_constraint(None, 'administrative_sggs', ['sgg_code'])
    op.drop_index(op.f('ix_administrative_sidos_sido_code'), table_name='administrative_sidos')
    op.create_unique_constraint(None, 'administrative_sidos', ['sido_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'administrative_sidos', type_='unique')
    op.create_index(op.f('ix_administrative_sidos_sido_code'), 'administrative_sidos', ['sido_code'], unique=True)
    op.drop_constraint(None, 'administrative_sggs', type_='unique')
    op.create_index(op.f('ix_administrative_sggs_sgg_code'), 'administrative_sggs', ['sgg_code'], unique=True)
    op.create_foreign_key(op.f('administrative_emds_sgg_code_fkey'), 'administrative_emds', 'administrative_sggs', ['sgg_code'], ['sgg_code'])
    op.drop_constraint(None, 'administrative_emds', type_='unique')
    op.create_index(op.f('ix_administrative_emds_emd_code'), 'administrative_emds', ['emd_code'], unique=True)
    # ### end Alembic commands ###
