"""add real_estate_transaction detail columns

Revision ID: 6240dc577ce3
Revises: 6b002b37f1f7
Create Date: 2026-02-15 19:13:15.226888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6240dc577ce3'
down_revision: Union[str, Sequence[str], None] = '6b002b37f1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standard_land_prices_pnu'), table_name='standard_land_prices')
    op.drop_table('standard_land_prices')
    op.add_column('official_land_prices', sa.Column('bjd_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('official_land_prices', sa.Column('special_land_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True))
    op.add_column('official_land_prices', sa.Column('special_land_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('official_land_prices', sa.Column('announcement_date', sa.Date(), nullable=True))
    op.add_column('official_land_prices', sa.Column('source_sigungu_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True))
    op.drop_column('official_land_prices', 'base_date')
    op.add_column('real_estate_transactions', sa.Column('sigungu', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('lot_number', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('main_lot_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('sub_lot_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('road_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('exclusive_area', sa.Float(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('land_area', sa.Float(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('floor_area', sa.Float(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('contract_area', sa.Float(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('floor', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('dong', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('build_year', sa.Integer(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('housing_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('buyer_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('seller_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('deal_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('broker_location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('registration_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('cancellation_date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('rent_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('deposit', sa.Integer(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('monthly_rent_amount', sa.Integer(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('contract_period', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('contract_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('renewal_right_used', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('previous_deposit', sa.Integer(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('previous_monthly_rent', sa.Integer(), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('land_category', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('use_area', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('road_condition', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    op.add_column('real_estate_transactions', sa.Column('share_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.create_index(op.f('ix_real_estate_transactions_building_name'), 'real_estate_transactions', ['building_name'], unique=False)
    op.create_index(op.f('ix_real_estate_transactions_sigungu'), 'real_estate_transactions', ['sigungu'], unique=False)
    op.create_index(op.f('ix_real_estate_transactions_transaction_date'), 'real_estate_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_real_estate_transactions_transaction_date'), table_name='real_estate_transactions')
    op.drop_index(op.f('ix_real_estate_transactions_sigungu'), table_name='real_estate_transactions')
    op.drop_index(op.f('ix_real_estate_transactions_building_name'), table_name='real_estate_transactions')
    op.drop_column('real_estate_transactions', 'share_type')
    op.drop_column('real_estate_transactions', 'road_condition')
    op.drop_column('real_estate_transactions', 'use_area')
    op.drop_column('real_estate_transactions', 'land_category')
    op.drop_column('real_estate_transactions', 'previous_monthly_rent')
    op.drop_column('real_estate_transactions', 'previous_deposit')
    op.drop_column('real_estate_transactions', 'renewal_right_used')
    op.drop_column('real_estate_transactions', 'contract_type')
    op.drop_column('real_estate_transactions', 'contract_period')
    op.drop_column('real_estate_transactions', 'monthly_rent_amount')
    op.drop_column('real_estate_transactions', 'deposit')
    op.drop_column('real_estate_transactions', 'rent_type')
    op.drop_column('real_estate_transactions', 'cancellation_date')
    op.drop_column('real_estate_transactions', 'registration_date')
    op.drop_column('real_estate_transactions', 'broker_location')
    op.drop_column('real_estate_transactions', 'deal_type')
    op.drop_column('real_estate_transactions', 'seller_type')
    op.drop_column('real_estate_transactions', 'buyer_type')
    op.drop_column('real_estate_transactions', 'housing_type')
    op.drop_column('real_estate_transactions', 'build_year')
    op.drop_column('real_estate_transactions', 'dong')
    op.drop_column('real_estate_transactions', 'floor')
    op.drop_column('real_estate_transactions', 'contract_area')
    op.drop_column('real_estate_transactions', 'floor_area')
    op.drop_column('real_estate_transactions', 'land_area')
    op.drop_column('real_estate_transactions', 'exclusive_area')
    op.drop_column('real_estate_transactions', 'building_name')
    op.drop_column('real_estate_transactions', 'road_name')
    op.drop_column('real_estate_transactions', 'sub_lot_number')
    op.drop_column('real_estate_transactions', 'main_lot_number')
    op.drop_column('real_estate_transactions', 'lot_number')
    op.drop_column('real_estate_transactions', 'sigungu')
    op.add_column('official_land_prices', sa.Column('base_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('official_land_prices', 'source_sigungu_code')
    op.drop_column('official_land_prices', 'announcement_date')
    op.drop_column('official_land_prices', 'special_land_name')
    op.drop_column('official_land_prices', 'special_land_code')
    op.drop_column('official_land_prices', 'bjd_name')
    op.create_table('standard_land_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('collected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pnu', sa.VARCHAR(length=19), autoincrement=False, nullable=False),
    sa.Column('bjd_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('jibun', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('base_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jimok_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('jimok_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('land_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('use_zone_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('use_zone_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('land_use_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('land_use_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('official_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_base_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], name=op.f('standard_land_prices_pnu_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('standard_land_prices_pkey')),
    sa.UniqueConstraint('pnu', 'base_year', name=op.f('uq_std_price_pnu_year'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_standard_land_prices_pnu'), 'standard_land_prices', ['pnu'], unique=False)
    # ### end Alembic commands ###
