"""

Revision ID: 62c51e1157ae
Revises: 1494dcb4fa70
Create Date: 2026-02-17 20:14:29.857735

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62c51e1157ae'
down_revision: str | Sequence[str] | None = '1494dcb4fa70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_land_and_forest_infos_pnu'), 'land_and_forest_infos', ['pnu'], unique=False)
    op.create_index(op.f('ix_land_characteristics_pnu'), 'land_characteristics', ['pnu'], unique=False)
    op.create_index(op.f('ix_land_ownerships_pnu'), 'land_ownerships', ['pnu'], unique=False)
    op.create_index(op.f('ix_land_use_plans_pnu'), 'land_use_plans', ['pnu'], unique=False)
    op.create_index(op.f('ix_official_land_prices_pnu'), 'official_land_prices', ['pnu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_official_land_prices_pnu'), table_name='official_land_prices')
    op.drop_index(op.f('ix_land_use_plans_pnu'), table_name='land_use_plans')
    op.drop_index(op.f('ix_land_ownerships_pnu'), table_name='land_ownerships')
    op.drop_index(op.f('ix_land_characteristics_pnu'), table_name='land_characteristics')
    op.drop_index(op.f('ix_land_and_forest_infos_pnu'), table_name='land_and_forest_infos')
    # ### end Alembic commands ###
