"""add building register models

Revision ID: 6b002b37f1f7
Revises: 170a324e55de
Create Date: 2026-02-15 17:09:00.742825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b002b37f1f7'
down_revision: Union[str, Sequence[str], None] = '170a324e55de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrative_divisions_code'), 'administrative_divisions', ['code'], unique=True)
    op.create_table('lots',
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('sido_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('sgg_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('emd_code', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('ri_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('is_mountain', sa.Boolean(), nullable=False),
    sa.Column('main_number', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('sub_number', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('jibun_address', sa.String(length=500), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pnu')
    )
    op.create_index(op.f('ix_lots_emd_code'), 'lots', ['emd_code'], unique=False)
    op.create_index(op.f('ix_lots_sgg_code'), 'lots', ['sgg_code'], unique=False)
    op.create_index(op.f('ix_lots_sido_code'), 'lots', ['sido_code'], unique=False)
    op.create_table('real_estate_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=True),
    sa.Column('property_type', sa.Enum('LAND', 'COMMERCIAL', 'DETACHED_HOUSE', 'ROW_HOUSE', 'APARTMENT', 'OFFICETEL', name='property_type_enum', create_constraint=True), nullable=False),
    sa.Column('transaction_type', sa.Enum('SALE', 'JEONSE', 'MONTHLY_RENT', name='transaction_type_enum', create_constraint=True), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_transactions_pnu'), 'real_estate_transactions', ['pnu'], unique=False)
    op.create_table('road_center_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('road_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('admin_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_center_lines_admin_code'), 'road_center_lines', ['admin_code'], unique=False)
    op.create_index(op.f('ix_road_center_lines_source_id'), 'road_center_lines', ['source_id'], unique=False)
    op.create_table('use_region_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('district_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('district_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('admin_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_region_districts_admin_code'), 'use_region_districts', ['admin_code'], unique=False)
    op.create_index(op.f('ix_use_region_districts_source_id'), 'use_region_districts', ['source_id'], unique=False)
    op.create_table('administrative_emds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('division_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.ForeignKeyConstraint(['division_code'], ['administrative_divisions.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrative_emds_code'), 'administrative_emds', ['code'], unique=True)
    op.create_index(op.f('ix_administrative_emds_division_code'), 'administrative_emds', ['division_code'], unique=False)
    op.create_table('ancillary_lands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ancillary_lands_pnu'), 'ancillary_lands', ['pnu'], unique=False)
    op.create_table('apartment_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('base_month', sa.Integer(), nullable=True),
    sa.Column('apt_type_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('apt_type_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('apt_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('dong_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('floor_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('ho_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('exclusive_area', sa.Float(), nullable=True),
    sa.Column('official_price', sa.Integer(), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'base_year', 'dong_name', 'ho_name', name='uq_apt_price')
    )
    op.create_index(op.f('ix_apartment_prices_pnu'), 'apartment_prices', ['pnu'], unique=False)
    op.create_table('building_register_ancillary_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mgm_bldrgst_pk', sqlmodel.sql.sqltypes.AutoString(length=33), nullable=False),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('atch_pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=True),
    sa.Column('created_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_register_ancillary_lots_atch_pnu'), 'building_register_ancillary_lots', ['atch_pnu'], unique=False)
    op.create_index(op.f('ix_building_register_ancillary_lots_mgm_bldrgst_pk'), 'building_register_ancillary_lots', ['mgm_bldrgst_pk'], unique=False)
    op.create_index(op.f('ix_building_register_ancillary_lots_pnu'), 'building_register_ancillary_lots', ['pnu'], unique=False)
    op.create_table('building_register_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mgm_bldrgst_pk', sqlmodel.sql.sqltypes.AutoString(length=33), nullable=False),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('ledger_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('dong_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ho_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('floor_type', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('floor_no', sa.Integer(), nullable=True),
    sa.Column('exclu_common_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('main_atch_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('main_use_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('created_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_register_areas_mgm_bldrgst_pk'), 'building_register_areas', ['mgm_bldrgst_pk'], unique=False)
    op.create_index(op.f('ix_building_register_areas_pnu'), 'building_register_areas', ['pnu'], unique=False)
    op.create_table('building_register_floor_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mgm_bldrgst_pk', sqlmodel.sql.sqltypes.AutoString(length=33), nullable=False),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('dong_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('floor_type', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('floor_type_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('floor_no', sa.Integer(), nullable=True),
    sa.Column('structure_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('main_use_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('main_atch_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('created_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_register_floor_details_mgm_bldrgst_pk'), 'building_register_floor_details', ['mgm_bldrgst_pk'], unique=False)
    op.create_index(op.f('ix_building_register_floor_details_pnu'), 'building_register_floor_details', ['pnu'], unique=False)
    op.create_table('building_register_generals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mgm_bldrgst_pk', sqlmodel.sql.sqltypes.AutoString(length=33), nullable=False),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('ledger_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('road_address', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('site_area', sa.Float(), nullable=True),
    sa.Column('building_area', sa.Float(), nullable=True),
    sa.Column('bcr', sa.Float(), nullable=True),
    sa.Column('total_floor_area', sa.Float(), nullable=True),
    sa.Column('far_area', sa.Float(), nullable=True),
    sa.Column('far', sa.Float(), nullable=True),
    sa.Column('main_use_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('household_count', sa.Integer(), nullable=True),
    sa.Column('family_count', sa.Integer(), nullable=True),
    sa.Column('main_bldcnt', sa.Integer(), nullable=True),
    sa.Column('atch_bldcnt', sa.Integer(), nullable=True),
    sa.Column('total_parking', sa.Integer(), nullable=True),
    sa.Column('approval_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('ho_count', sa.Integer(), nullable=True),
    sa.Column('created_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mgm_bldrgst_pk', name='uq_bldrgst_general_pk')
    )
    op.create_index(op.f('ix_building_register_generals_mgm_bldrgst_pk'), 'building_register_generals', ['mgm_bldrgst_pk'], unique=False)
    op.create_index(op.f('ix_building_register_generals_pnu'), 'building_register_generals', ['pnu'], unique=False)
    op.create_table('building_register_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('mgm_bldrgst_pk', sqlmodel.sql.sqltypes.AutoString(length=33), nullable=False),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('ledger_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('road_address', sqlmodel.sql.sqltypes.AutoString(length=400), nullable=True),
    sa.Column('dong_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('main_atch_type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('site_area', sa.Float(), nullable=True),
    sa.Column('building_area', sa.Float(), nullable=True),
    sa.Column('bcr', sa.Float(), nullable=True),
    sa.Column('total_floor_area', sa.Float(), nullable=True),
    sa.Column('far_area', sa.Float(), nullable=True),
    sa.Column('far', sa.Float(), nullable=True),
    sa.Column('structure_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('main_use_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('household_count', sa.Integer(), nullable=True),
    sa.Column('family_count', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('above_ground_floors', sa.Integer(), nullable=True),
    sa.Column('underground_floors', sa.Integer(), nullable=True),
    sa.Column('approval_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('ho_count', sa.Integer(), nullable=True),
    sa.Column('created_date', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mgm_bldrgst_pk', name='uq_bldrgst_header_pk')
    )
    op.create_index(op.f('ix_building_register_headers_mgm_bldrgst_pk'), 'building_register_headers', ['mgm_bldrgst_pk'], unique=False)
    op.create_index(op.f('ix_building_register_headers_pnu'), 'building_register_headers', ['pnu'], unique=False)
    op.create_table('gis_building_integrated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('bjd_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('special_land_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('use_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('structure_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('building_area', sa.Float(), nullable=True),
    sa.Column('approval_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('total_floor_area', sa.Float(), nullable=True),
    sa.Column('site_area', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('building_coverage_ratio', sa.Float(), nullable=True),
    sa.Column('floor_area_ratio', sa.Float(), nullable=True),
    sa.Column('building_id', sqlmodel.sql.sqltypes.AutoString(length=28), nullable=True),
    sa.Column('is_violation', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('building_dong_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('above_ground_floors', sa.Integer(), nullable=True),
    sa.Column('underground_floors', sa.Integer(), nullable=True),
    sa.Column('data_change_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'building_id', name='uq_gis_building_pnu_bid')
    )
    op.create_index(op.f('ix_gis_building_integrated_pnu'), 'gis_building_integrated', ['pnu'], unique=False)
    op.create_table('individual_house_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('base_month', sa.Integer(), nullable=True),
    sa.Column('building_floor_area', sa.Float(), nullable=True),
    sa.Column('land_area', sa.Float(), nullable=True),
    sa.Column('total_floor_area', sa.Float(), nullable=True),
    sa.Column('house_price', sa.Integer(), nullable=True),
    sa.Column('is_standard', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'base_year', name='uq_ind_house_pnu_year')
    )
    op.create_index(op.f('ix_individual_house_prices_pnu'), 'individual_house_prices', ['pnu'], unique=False)
    op.create_table('land_and_forest_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('jimok_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('jimok_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('ownership_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('ownership_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('owner_count', sa.Integer(), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'data_year', name='uq_land_forest_pnu_year')
    )
    op.create_index(op.f('ix_land_and_forest_infos_pnu'), 'land_and_forest_infos', ['pnu'], unique=False)
    op.create_table('land_characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('jimok_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('jimok_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('land_area', sa.Float(), nullable=True),
    sa.Column('use_zone_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('use_zone_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('land_use_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('land_use_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('road_side_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('official_price', sa.Integer(), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'data_year', name='uq_land_char_pnu_year')
    )
    op.create_index(op.f('ix_land_characteristics_pnu'), 'land_characteristics', ['pnu'], unique=False)
    op.create_table('land_use_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('use_district_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('use_district_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('inclusion_code', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'data_year', name='uq_land_use_pnu_year')
    )
    op.create_index(op.f('ix_land_use_plans_pnu'), 'land_use_plans', ['pnu'], unique=False)
    op.create_table('official_land_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=True),
    sa.Column('price_per_sqm', sa.Integer(), nullable=True),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('base_month', sa.Integer(), nullable=True),
    sa.Column('is_standard', sa.Boolean(), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'base_year', name='uq_official_price_pnu_year')
    )
    op.create_index(op.f('ix_official_land_prices_pnu'), 'official_land_prices', ['pnu'], unique=False)
    op.create_table('standard_land_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('pnu', sqlmodel.sql.sqltypes.AutoString(length=19), nullable=False),
    sa.Column('bjd_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('jibun', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('jimok_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('jimok_name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('land_area', sa.Float(), nullable=True),
    sa.Column('use_zone_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('use_zone_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('land_use_code', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=True),
    sa.Column('land_use_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('official_price', sa.Integer(), nullable=True),
    sa.Column('data_base_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.ForeignKeyConstraint(['pnu'], ['lots.pnu'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pnu', 'base_year', name='uq_std_price_pnu_year')
    )
    op.create_index(op.f('ix_standard_land_prices_pnu'), 'standard_land_prices', ['pnu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standard_land_prices_pnu'), table_name='standard_land_prices')
    op.drop_table('standard_land_prices')
    op.drop_index(op.f('ix_official_land_prices_pnu'), table_name='official_land_prices')
    op.drop_table('official_land_prices')
    op.drop_index(op.f('ix_land_use_plans_pnu'), table_name='land_use_plans')
    op.drop_table('land_use_plans')
    op.drop_index(op.f('ix_land_characteristics_pnu'), table_name='land_characteristics')
    op.drop_table('land_characteristics')
    op.drop_index(op.f('ix_land_and_forest_infos_pnu'), table_name='land_and_forest_infos')
    op.drop_table('land_and_forest_infos')
    op.drop_index(op.f('ix_individual_house_prices_pnu'), table_name='individual_house_prices')
    op.drop_table('individual_house_prices')
    op.drop_index(op.f('ix_gis_building_integrated_pnu'), table_name='gis_building_integrated')
    op.drop_table('gis_building_integrated')
    op.drop_index(op.f('ix_building_register_headers_pnu'), table_name='building_register_headers')
    op.drop_index(op.f('ix_building_register_headers_mgm_bldrgst_pk'), table_name='building_register_headers')
    op.drop_table('building_register_headers')
    op.drop_index(op.f('ix_building_register_generals_pnu'), table_name='building_register_generals')
    op.drop_index(op.f('ix_building_register_generals_mgm_bldrgst_pk'), table_name='building_register_generals')
    op.drop_table('building_register_generals')
    op.drop_index(op.f('ix_building_register_floor_details_pnu'), table_name='building_register_floor_details')
    op.drop_index(op.f('ix_building_register_floor_details_mgm_bldrgst_pk'), table_name='building_register_floor_details')
    op.drop_table('building_register_floor_details')
    op.drop_index(op.f('ix_building_register_areas_pnu'), table_name='building_register_areas')
    op.drop_index(op.f('ix_building_register_areas_mgm_bldrgst_pk'), table_name='building_register_areas')
    op.drop_table('building_register_areas')
    op.drop_index(op.f('ix_building_register_ancillary_lots_pnu'), table_name='building_register_ancillary_lots')
    op.drop_index(op.f('ix_building_register_ancillary_lots_mgm_bldrgst_pk'), table_name='building_register_ancillary_lots')
    op.drop_index(op.f('ix_building_register_ancillary_lots_atch_pnu'), table_name='building_register_ancillary_lots')
    op.drop_table('building_register_ancillary_lots')
    op.drop_index(op.f('ix_apartment_prices_pnu'), table_name='apartment_prices')
    op.drop_table('apartment_prices')
    op.drop_index(op.f('ix_ancillary_lands_pnu'), table_name='ancillary_lands')
    op.drop_table('ancillary_lands')
    op.drop_index(op.f('ix_administrative_emds_division_code'), table_name='administrative_emds')
    op.drop_index(op.f('ix_administrative_emds_code'), table_name='administrative_emds')
    op.drop_table('administrative_emds')
    op.drop_index(op.f('ix_use_region_districts_source_id'), table_name='use_region_districts')
    op.drop_index(op.f('ix_use_region_districts_admin_code'), table_name='use_region_districts')
    op.drop_table('use_region_districts')
    op.drop_index(op.f('ix_road_center_lines_source_id'), table_name='road_center_lines')
    op.drop_index(op.f('ix_road_center_lines_admin_code'), table_name='road_center_lines')
    op.drop_table('road_center_lines')
    op.drop_index(op.f('ix_real_estate_transactions_pnu'), table_name='real_estate_transactions')
    op.drop_table('real_estate_transactions')
    op.drop_index(op.f('ix_lots_sido_code'), table_name='lots')
    op.drop_index(op.f('ix_lots_sgg_code'), table_name='lots')
    op.drop_index(op.f('ix_lots_emd_code'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_administrative_divisions_code'), table_name='administrative_divisions')
    op.drop_table('administrative_divisions')
    # ### end Alembic commands ###
