"""drop_ancillary_lands_table

Revision ID: af6aabc26309
Revises: 6cdec6e97f6d
Create Date: 2026-02-18 14:03:46.371789

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'af6aabc26309'
down_revision: str | Sequence[str] | None = '6cdec6e97f6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ancillary_lands_pnu'), table_name='ancillary_lands')
    op.drop_table('ancillary_lands')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ancillary_lands',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pnu', sa.VARCHAR(length=19), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ancillary_lands_pkey'))
    )
    op.create_index(op.f('ix_ancillary_lands_pnu'), 'ancillary_lands', ['pnu'], unique=False)
    # ### end Alembic commands ###
