"""add geometry to reports

Revision ID: b467517efbf5
Revises: 2e14c8b34c3a
Create Date: 2026-02-22 15:16:23.689308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'b467517efbf5'
down_revision: Union[str, Sequence[str], None] = '2e14c8b34c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('reports', sa.Column('geometry', Geometry(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_geospatial_index('idx_reports_geometry', 'reports', ['geometry'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_reports_geometry', table_name='reports', postgresql_using='gist', column_name='geometry')
    op.drop_geospatial_column('reports', 'geometry')
    # ### end Alembic commands ###
