"""drop land_use_code, ownership_code, use_zone_code from lots

Revision ID: b59b6388bfb4
Revises: d85a35a9f086
Create Date: 2026-02-18 16:07:08.195311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b59b6388bfb4'
down_revision: Union[str, Sequence[str], None] = 'd85a35a9f086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'land_use_code')
    op.drop_column('lots', 'ownership_code')
    op.drop_column('lots', 'use_zone_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('use_zone_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('lots', sa.Column('ownership_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('lots', sa.Column('land_use_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
